### ISSUE TITLE
Request - Block Items via JEI - 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [konwboj/MagicClover#12]
So now that I think about how epic this mod was I also realized a major flaw ... blocking items via config or command line is a pain why not add op only block via JEI? So basically if you added a check box in the JEI config you could deem certain items unobtainable via magic clover. In this way this will give admins greater control over the mod. Also should the mod dislike a certain item we can quickly remove it from the drop pool!

Another thing is I remember sometimes the mod would spawn the shell of an item not the item itself like a texture-less sword that swinging crashes the game and such.

**Comment by konwboj** [comment]
Sorry, but I'm no longer actively adding features to this mod.
