### ISSUE TITLE
No texture for item?

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [konwboj/MagicClover#14]
Hello,

the four leaves clover item has no texture, it's like an invisible item, i can see i have them when they stack because of the number in the inventory, but no texture, did i miss something?

Thank you for your time.

**Comment by konwboj** [comment]
Could you post more details (your MC, Forge and mod versions)?

**Comment by Ganjalf-Amsterdoom** [comment]
Hello again,

so MC is 1.12.2 and forge is Forge Mod Loader version 14.23.1.2555 for Minecraft 1.12.2, as for the mod I think i'm at latest version since twitch/curse app doesn't show any update.

Thank you for your time.

**Comment by konwboj** [comment]
Fixed in the latest version
