### ISSUE TITLE
Whitelist does not work

### ISSUE THREAD

**Issue by Mumberthrax** [konwboj/MagicClover#6]
In the config file, it states: 

>  # If not empty, these items will be only ones that drop from clover. Formatted like other lists in this config. Supports item names (like minecraft:dirt)!
>    S:"Item Whitelist"

however, entering something like minecraft:wheat_seeds into this section seems to have no effect - all the items from the game not on the blacklist drop from using the clovers, instead of only wheat seeds as expected.

Minecraft 1.8, forge 11.14.4.1563, Magic Clover 1.8-0.6.2, Java 8, Windows 7

**Comment by Blue64** [comment]
I would offer help, but I'm more of a 1.7.10 guy myself, I also have no idea why that would fail lol

**Comment by konwboj** [comment]
Fixed in 0.7. Going to release it tommorow.
